### ISSUE TITLE
[JOSS review]: community guidelines

### ISSUE THREAD

**Issue by arokem** [DTUComputeStatisticsAndDataAnalysis/MBPLS#8]
From the JOSS review criteria: "Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support?". Please add these items to your documentation. Consider using a [Issue template](https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/) and adding a [CONTRIBUTING.md](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) file.

**Comment by lvermue** [comment]
Resolved by following commits:
https://github.com/DTUComputeStatisticsAndDataAnalysis/MBPLS/commit/1cc8ac6d0a8c20ef18ccb77931b7acb3e6ad746e, 
https://github.com/DTUComputeStatisticsAndDataAnalysis/MBPLS/commit/923a50010b595901950036308fed6094b021b2df and 
https://github.com/DTUComputeStatisticsAndDataAnalysis/MBPLS/commit/9181d728472a369fed9b91c0958e136958bdaa5f.
