### ISSUE TITLE
Computation of diff_t in the NIPALS Algorithm.

### ISSUE THREAD

**Issue by sten2lu** [DTUComputeStatisticsAndDataAnalysis/MBPLS#9]
In the line 855 of the MultiBlockPLS implementation in mbpls.py .

You use: diff_t = np.sum(superscores_old - superscores)

While actually the Euclidean Metric should be used as far as I understand.
with: diff_t = np.sum((superscores_old - superscores)**2)
or diff_t = np.sum((superscores_old - superscores)**2)**0.5

Could you clarify your use of this "metric" for the vectors please, in case I am mistaken?

**Comment by b0nsaii** [comment]
You are right @sten2lu ! Thank you for spotting this bug. We will have it fixed asap.
